import pyautogui
import time

time.sleep(2)
print(pyautogui.position())
pyautogui.moveTo(901,1056)
pyautogui.click(button="left")
pyautogui.moveTo(933,522)
pyautogui.click(button="left")
pyautogui.write("flipkart")
pyautogui.press("enter")
pyautogui.moveTo(244,398)
time.sleep(2)
pyautogui.click(button="left")
pyautogui.moveTo(801,172)
time.sleep(2)
pyautogui.click(button="left")
pyautogui.write("keybord")
pyautogui.press("enter")
pyautogui.moveTo(560,578)
time.sleep(2)
pyautogui.click(button="left")
pyautogui.moveTo(600,873)
time.sleep(2)
pyautogui.click(button="left")
time.sleep(2)
pyautogui.moveTo(460,556)
pyautogui.click(button="left")
time.sleep(2)
pyautogui.scroll(-5000)
pyautogui.moveTo(1014,735)